apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-custodian-ec2-ami
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<CLUSTER_NAME>-cloud-custodian-ec2-ami-role
